#!/usr/bin/env python3
"""Blind listening page for text -> preset: for each prompt, sound A and sound B (generated by the v3
generator or selected from the bank, in a random order), each rated 1-5 for "matches the description".

The page only carries opaque ids; which sound is which stays in data/v3/listening_prompts/key.json.

    python scripts/v3/generate_v3.py --prompts prompts.json --out data/v3/generations
    python scripts/v3/listening_prompts.py --generations data/v3/generations
"""

from __future__ import annotations

import argparse
import hashlib
import json
import random
import sys
from pathlib import Path

import numpy as np

BASE_DIR = Path(__file__).resolve().parents[2]
if str(BASE_DIR) not in sys.path:
    sys.path.append(str(BASE_DIR))

from scripts.v3.listening_v3 import clip, write_mp3  # noqa: E402
from src.presets import dx7_render  # noqa: E402
from src.presets import matching as M  # noqa: E402
from src.synth.engine_v3 import render_physical  # noqa: E402

BANK = BASE_DIR / "data" / "v3" / "bank"
TEMPLATE = Path(__file__).with_name("listening_v3_template.html")
NOTE = ("Écoute à l'aveugle : pour chaque description, deux sons. L'un est créé par l'IA (génération), l'autre est "
        "un vrai preset choisi dans la banque (sélection), dans un ordre caché. Note chacun de 1 à 5 selon qu'il "
        "correspond à la description.")


def notes_audio(kind: str, preset) -> list:
    if kind == "dx7":
        return [dx7_render.render(preset, note=n, velocity=M.VELOCITY, hold_seconds=M.HOLD_SECONDS,
                                  total_seconds=M.TOTAL_SECONDS) for n in M.NOTES]
    return [render_physical(np.asarray(preset, dtype=np.float64), n, M.VELOCITY / 127, M.HOLD_SECONDS,
                            M.TOTAL_SECONDS, M.SR, 7) for n in M.NOTES]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--generations", type=Path, default=BASE_DIR / "data" / "v3" / "generations")
    parser.add_argument("--out", type=Path, default=BASE_DIR / "data" / "v3" / "listening_prompts")
    parser.add_argument("--round", default="p1")
    args = parser.parse_args()

    from src.v3 import codecs

    rows = json.loads((args.generations / "generations.json").read_text(encoding="utf-8"))
    z = np.load(BANK / "bank.npz")
    ids = [json.loads(line)["id"] for line in open(BANK / "entries.jsonl", encoding="utf-8")]
    index = {pid: i for i, pid in enumerate(ids)}
    audio_dir = args.out / "audio"
    audio_dir.mkdir(parents=True, exist_ok=True)
    rng = random.Random(f"harmonia-{args.round}")  # nosec B311 - shuffles A/B order, not security-sensitive
    items, key = [], {}
    for n, row in enumerate(rows):
        vector = np.asarray(row["generated_vector"])
        generated = (row["generated_kind"], codecs.dx7_decode(vector) if row["generated_kind"] == "dx7"
                     else codecs.analog_decode(vector))
        i = index[row["selected"]["id"]]
        selected = (row["selected"]["kind"], dx7_render.from_patch(bytes(z["dx7"][i])) if row["selected"]["kind"] == "dx7"
                    else z["analog"][i].astype(np.float64))
        pair = [("generation", generated), ("selection", selected)]
        rng.shuffle(pair)
        for letter, (system, (kind, preset)) in zip("AB", pair):
            opaque = hashlib.sha1(f"{args.round}-{n}-{letter}".encode(), usedforsecurity=False).hexdigest()[:12]
            path = f"audio/{opaque}.mp3"
            write_mp3(args.out / path, clip(notes_audio(kind, preset)))
            item_id = f"prompt-{args.round}-{n:03d}-{letter}"
            key[item_id] = {"system": system, "kind": kind, "prompt": row["prompt"]}
            items.append({"id": item_id, "source": "Prompts", "name": f"{letter} · {row['prompt']}", "category": "",
                          "author": "", "license": "", "clips": {"dx7": path}})
    page = TEMPLATE.read_text(encoding="utf-8").replace("/*ITEMS*/[]", json.dumps(items, ensure_ascii=False))
    page = page.replace('/*ROUND*/""', json.dumps(NOTE, ensure_ascii=False))
    page = page.replace("Mode DX7 (Harmonia)", "Son").replace("Son réussi ?", "Correspond ?")
    (args.out / "index.html").write_text(page, encoding="utf-8")
    (args.out / "key.json").write_text(json.dumps(key, ensure_ascii=False, indent=1), encoding="utf-8")
    print(f"{len(items)} sounds for {len(rows)} prompts -> {args.out / 'index.html'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
